#fetch one person with existant id
GET https://fs-gregorian-phonebook.fly.dev/api/persons/653404c4948b4706b923694c
Content-Type: application/json
###

#fetch with non existant
#to make a valid id replace some numbers in an id that is in the #database but dont replace the letters.
GET https://fs-gregorian-phonebook.fly.dev/api/persons/652404c4941b4706b923694c
Content-Type: application/json
###

#fetch with malformed
GET https://fs-gregorian-phonebook.fly.dev/api/persons/653404c4948b4706b923694
Content-Type: application/json
###